project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "About"
        contents:
          - index.qmd
      - section: "Information"
        contents:
          - conferences.qmd
          - people.qmd
          - contact.qmd             
      - section: "News"
        contents:
          - posts.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    smooth-scroll: true
